---
image: ubuntu:rolling

check-job:
  tags:
    - arm64

  script:
    - apt-get update
    - apt-get install -y make python3 python3-yaml python3-jsonschema
      python3-packaging yamllint flake8 shellcheck python3-junit.xml git
    - make -k check

  artifacts:
    when: always

    paths:
      - test-*.log

doc-job:
  tags:
    - arm64

  script:
    - apt-get update
    - apt-get install -y make pandoc texlive-latex-base
      texlive-latex-recommended
    - make doc

  artifacts:
    paths:
      - README.pdf
