---
$id: "https://gitlab.arm.com/systemready/edk2-test-parser/-/raw/main/\
    schemas/config-schema.yaml"
$schema: https://json-schema.org/draft/2020-12/schema
title: SCT Parser configuration schema
description: |
    The SCT Parser uses configurations files in YAML format to perform a number
    of transformations on the tests results.

    This schema describes requirements on the configuration file, which can be
    verified with the validate.py script. See the README for details.
type: array
minItems: 1
uniqueItems: true
items:
    type: object
    properties:
        rule:
            type: string
        criteria:
            type: object
            properties:
                descr:
                    '$ref': './common-schema.yaml#/$defs/descr'
                device path:
                    type: string
                group:
                    enum:
                        - BootServicesTest
                        - ConsoleSupportTest
                        - DevicePathProcotols
                        - GenericTest
                        - HIITest
                        - MediaAccessTest
                        - NetworkSupportTest
                        - RuntimeServicesTest
                        - SecureTechTest
                guid:
                    '$ref': './common-schema.yaml#/$defs/guid'
                name:
                    type: string
                log:
                    type: string
                result:
                    enum:
                        - DROPPED
                        - FAILURE
                        - SKIPPED
                        - WARNING
                revision:
                    type: string
                    pattern: '0x0*1000[012]'
                set guid:
                    '$ref': './common-schema.yaml#/$defs/guid'
                sub set:
                    '$ref': './common-schema.yaml#/$defs/sub-set'
                test set:
                    enum:
                        - BBSRVariableSizeTest
                        - DevicePathProcotolTest
                        - DevicePathUtilitiesProcotolTest
                        - EFICompliantTest
                        - EventTimerandPriorityServicesTest
                        - HIIDatabaseProtocolTest
                        - ImageServicesTest
                        - LoadedImageProtocolTest
                        - MemoryAllocationServicesTest
                        - MiscBootServicesTest
                        - MiscRuntimeServicesTest
                        - ProtocolHandlerServicesTest
                        - RNGProtocolTest
                        - SBBRRuntimeServicesTest
                        - SbbrBootServices
                        - SbbrEfiSpecVerLvl
                        - SbbrSysEnvConfig
                        - SimpleFileSystemProtocolTest
                        - SimpleInputProtocolTest
                        - SimpleNetworkProtocolTest
                        - SimpleOutputProtocolTest
                        - SimpleTextInputExProtocolTest
                        - TimeServicesTest
                        - VariableServicesTest
            additionalProperties: false
            minProperties: 1
        update:
            type: object
            properties:
                comments:
                    type: string
                result:
                    enum:
                        - DROPPED
                        - FAILURE
                        - IGNORED
                        - KNOWN ACS LIMITATION
                        - KNOWN SIZE LIMITATION
                        - KNOWN U-BOOT LIMITATION
                        - SKIPPED
                        - WARNING
            additionalProperties: false
            minProperties: 1
    required:
        - rule
        - criteria
        - update
    additionalProperties: false
