---
name: CI
# yamllint disable-line rule:truthy
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and check
        run: |
          sudo apt install flake8
          make check
